/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Main.guielements;

import Main.FileReader;

/**
 *
 * @author ricar
 */
public class MainFrame extends javax.swing.JFrame {

    /**
     * Creates new form MainFrame
     */
    public MainFrame() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jButtonExit = new javax.swing.JButton();
        jButtonLoad = new javax.swing.JButton();
        jButtonNext = new javax.swing.JButton();
        jButtonRestart = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabelIR = new javax.swing.JLabel();
        jLabelAC = new javax.swing.JLabel();
        jLabelPC = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabelAX = new javax.swing.JLabel();
        jLabelBX = new javax.swing.JLabel();
        jLabelCX = new javax.swing.JLabel();
        jLabelDX = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTableNormal = new javax.swing.JTable();
        jScrollPane3 = new javax.swing.JScrollPane();
        jTableBinary = new javax.swing.JTable();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Computer Simulation Program");
        setResizable(false);

        jButtonExit.setText("Exit");
        jButtonExit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonExitActionPerformed(evt);
            }
        });

        jButtonLoad.setText("Load File");
        jButtonLoad.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonLoadActionPerformed(evt);
            }
        });

        jButtonNext.setText("Next Step");
        jButtonNext.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonNextActionPerformed(evt);
            }
        });

        jButtonRestart.setText("Restart");
        jButtonRestart.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonRestartActionPerformed(evt);
            }
        });

        jLabel1.setText("Memory:");

        jLabel2.setText("0-19: Reserved");

        jLabelIR.setText("IR: Empty");

        jLabelAC.setText("AC: 0");

        jLabelPC.setText("PC: Empty");

        jLabel6.setText("Registers:");

        jLabelAX.setText("AX: 0");

        jLabelBX.setText("BX: 0");

        jLabelCX.setText("CX: 0");

        jLabelDX.setText("DX: 0");

        jLabel11.setText("Memory (Binary):");

        jLabel12.setText("0-19: Reserved");

        jTableNormal.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {"20", "40", "60", "80"},
                {"21", "41", "61", "81"},
                {"22", "42", "62", "82"},
                {"23", "43", "63", "83"},
                {"24", "44", "64", "84"},
                {"25", "45", "65", "85"},
                {"26", "46", "66", "86"},
                {"27", "47", "67", "87"},
                {"28", "48", "68", "88"},
                {"29", "49", "69", "89"},
                {"30", "50", "70", "90"},
                {"31", "51", "71", "91"},
                {"32", "52", "72", "92"},
                {"33", "53", "73", "93"},
                {"34", "54", "74", "94"},
                {"35", "55", "75", "95"},
                {"36", "56", "76", "96"},
                {"37", "57", "77", "97"},
                {"38", "58", "78", "98"},
                {"39", "59", "79", "99"}
            },
            new String [] {
                "20-39", "40-59", "60-79", "80-99"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class
            };
            boolean[] canEdit = new boolean [] {
                false, false, false, false
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane1.setViewportView(jTableNormal);

        jTableBinary.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {"20", "40", "60", "80"},
                {"21", "41", "61", "81"},
                {"22", "42", "62", "82"},
                {"23", "43", "63", "83"},
                {"24", "44", "64", "84"},
                {"25", "45", "65", "85"},
                {"26", "46", "66", "86"},
                {"27", "47", "67", "87"},
                {"28", "48", "68", "88"},
                {"29", "49", "69", "89"},
                {"30", "50", "70", "90"},
                {"31", "51", "71", "91"},
                {"32", "52", "72", "92"},
                {"33", "53", "73", "93"},
                {"34", "54", "74", "94"},
                {"35", "55", "75", "95"},
                {"36", "56", "76", "96"},
                {"37", "57", "77", "97"},
                {"38", "58", "78", "98"},
                {"39", "59", "79", "99"}
            },
            new String [] {
                "20-39", "40-59", "60-79", "80-99"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class
            };
            boolean[] canEdit = new boolean [] {
                false, false, false, false
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane3.setViewportView(jTableBinary);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jButtonLoad)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jButtonNext)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jButtonRestart)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jButtonExit))
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel2)
                            .addComponent(jLabel1))
                        .addGap(393, 393, 393))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)))
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel12)
                            .addComponent(jLabel11))
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(2, 2, 2)
                        .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabelDX)
                            .addComponent(jLabelCX)
                            .addComponent(jLabelBX)
                            .addComponent(jLabelAX)
                            .addComponent(jLabel6)
                            .addComponent(jLabelPC)
                            .addComponent(jLabelAC)
                            .addComponent(jLabelIR))
                        .addGap(131, 131, 131))))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel1)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabel2))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel11)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabel12)))
                .addGap(15, 15, 15)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabelIR)
                        .addGap(18, 18, 18)
                        .addComponent(jLabelAC)
                        .addGap(18, 18, 18)
                        .addComponent(jLabelPC)
                        .addGap(70, 70, 70)
                        .addComponent(jLabel6)
                        .addGap(18, 18, 18)
                        .addComponent(jLabelAX)
                        .addGap(18, 18, 18)
                        .addComponent(jLabelBX)
                        .addGap(18, 18, 18)
                        .addComponent(jLabelCX)
                        .addGap(18, 18, 18)
                        .addComponent(jLabelDX))
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButtonExit)
                    .addComponent(jButtonLoad)
                    .addComponent(jButtonNext)
                    .addComponent(jButtonRestart)))
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void jButtonRestartActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonRestartActionPerformed
        // TODO add your handling code here:
        jTableNormal.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {"20", "40", "60", "80"},
                {"21", "41", "61", "81"},
                {"22", "42", "62", "82"},
                {"23", "43", "63", "83"},
                {"24", "44", "64", "84"},
                {"25", "45", "65", "85"},
                {"26", "46", "66", "86"},
                {"27", "47", "67", "87"},
                {"28", "48", "68", "88"},
                {"29", "49", "69", "89"},
                {"30", "50", "70", "90"},
                {"31", "51", "71", "91"},
                {"32", "52", "72", "92"},
                {"33", "53", "73", "93"},
                {"34", "54", "74", "94"},
                {"35", "55", "75", "95"},
                {"36", "56", "76", "96"},
                {"37", "57", "77", "97"},
                {"38", "58", "78", "98"},
                {"39", "59", "79", "99"}
            },
            new String [] {
                "20-39", "40-59", "60-79", "80-99"
            }));
        
        jTableBinary.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {"20", "40", "60", "80"},
                {"21", "41", "61", "81"},
                {"22", "42", "62", "82"},
                {"23", "43", "63", "83"},
                {"24", "44", "64", "84"},
                {"25", "45", "65", "85"},
                {"26", "46", "66", "86"},
                {"27", "47", "67", "87"},
                {"28", "48", "68", "88"},
                {"29", "49", "69", "89"},
                {"30", "50", "70", "90"},
                {"31", "51", "71", "91"},
                {"32", "52", "72", "92"},
                {"33", "53", "73", "93"},
                {"34", "54", "74", "94"},
                {"35", "55", "75", "95"},
                {"36", "56", "76", "96"},
                {"37", "57", "77", "97"},
                {"38", "58", "78", "98"},
                {"39", "59", "79", "99"}
            },
            new String [] {
                "20-39", "40-59", "60-79", "80-99"
            }));
        
        jLabelIR.setText("IR: Empty");
        jLabelAC.setText("AC: 0");
        jLabelPC.setText("PC: Empty");
        
       //Registers:
        jLabelAX.setText("AX: 0");
        jLabelBX.setText("BX: 0");
        jLabelCX.setText("CX: 0");
        jLabelDX.setText("DX: 0");
        
    }//GEN-LAST:event_jButtonRestartActionPerformed

    private void jButtonExitActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonExitActionPerformed
        // TODO add your handling code here:
        System.exit(0);
    }//GEN-LAST:event_jButtonExitActionPerformed

    private void jButtonLoadActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonLoadActionPerformed
        // TODO add your handling code here:
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new LoadWarning().setVisible(true);
            }
        });
        
    }//GEN-LAST:event_jButtonLoadActionPerformed

    private void jButtonNextActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonNextActionPerformed
        // TODO add your handling code here:
        jTableNormal.setValueAt("LOL", 1, 1);
    }//GEN-LAST:event_jButtonNextActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButtonExit;
    private javax.swing.JButton jButtonLoad;
    private javax.swing.JButton jButtonNext;
    private javax.swing.JButton jButtonRestart;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabelAC;
    private javax.swing.JLabel jLabelAX;
    private javax.swing.JLabel jLabelBX;
    private javax.swing.JLabel jLabelCX;
    private javax.swing.JLabel jLabelDX;
    private javax.swing.JLabel jLabelIR;
    private javax.swing.JLabel jLabelPC;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JTable jTableBinary;
    private javax.swing.JTable jTableNormal;
    // End of variables declaration//GEN-END:variables
}
